export const data = [
	{
		id: 1,
		img: './ico/nature.svg',
		name: 'Природа',
		type: 'park',
	},
	{
		id: 2,
		img: './ico/culture.png',
		name: 'Культура',
		type: 'museum',
	},
	{
		id: 3,
		img: './ico/history.png',
		name: 'История',
		type: 'art_gallery',
	},
	{
		id: 4,
		img: './ico/religion.png',
		name: 'Религия',
		type: 'church',
	},
	{
		id: 5,
		img: './ico/china-tower.png',
		name: 'Архитектура',
		type: 'church?????',
	},
	{
		id: 6,
		img: './ico/factory.png',
		name: 'Индустриальные объекты',
		type: 'bus_stop',
	},
	{
		id: 7,
		img: './ico/other.png',
		name: '	Разное',
		type: 'church???????',
	},
	{
		id: 8,
		img: './ico/ferris.png',
		name: 'Развлечения',
		type: 'tourist_attraction',
	},
	{
		id: 9,
		img: './ico/sport-soccer.png',
		name: 'Спорт',
		type: 'sports_club',
	},
	{
		id: 10,
		img: './ico/18+.png',
		name: '18+',
		type: 'night_club',
	},
	{
		id: 11,
		img: './ico/car-rear.png',
		name: 'Авто',
		type: 'car_dealer',
	},
	{
		id: 12,
		img: './ico/gas_station.png',
		name: 'Заправки',
		type: 'gas_station',
	},
	{
		id: 13,
		img: './ico/bicycle.png',
		name: 'Велосипеды',
		type: 'bicycle_store',
	},
	{
		id: 14,
		img: './ico/solar_shop.png',
		name: 'Магазины',
		type: 'market',
	},
	{
		id: 15,
		img: './ico/food.png',
		name: 'Еда',
		type: 'pizza_restaurant',
	},
	{
		id: 16,
		img: './ico/coffee.png',
		name: 'Кофе/чай',
		type: 'cafe',
	},
	{
		id: 17,
		img: './ico/bank.png',
		name: 'Банки',
		type: 'bank',
	},
	{
		id: 18,
		img: './ico/solid_bed.png',
		name: 'Место для сна',
		type: 'hostel',
	},
]
