export const icons: Record<string, string> = {
	// культура
	art_gallery: './ico/history.png',
	museum: './ico/culture.png',
	performing_arts_theater: './ico/culture.png',

	// Автомобильная промышленность
	car_dealer: './ico/car-rear.png',
	car_rental: './ico/car-rear.png',
	car_repair: './ico/car-rear.png',
	car_wash: './ico/car-rear.png',
	electric_vehicle_charging_station: './ico/car-rear.png',
	parking: './ico/car-rear.png',
	rest_stop: './ico/car-rear.png',

	gas_station: './ico/gas_station.png',

	//Финансы
	accounting: './ico/bank.png',
	atm: './ico/bank.png',
	bank: './ico/bank.png',

	// Проживание
	bed_and_breakfast: './ico/solid_bed.png',
	campground: './ico/solid_bed.png',
	camping_cabin: './ico/solid_bed.png',
	cottage: './ico/solid_bed.png',
	extended_stay_hotel: './ico/solid_bed.png',
	farmstay: './ico/solid_bed.png',
	guest_house: './ico/solid_bed.png',
	hostel: './ico/solid_bed.png',
	hotel: './ico/solid_bed.png',
	lodging: './ico/solid_bed.png',
	motel: './ico/solid_bed.png',
	private_guest_room: './ico/solid_bed.png',
	resort_hotel: './ico/solid_bed.png',
	rv_park: './ico/solid_bed.png',

	//Места поклонения
	church: './ico/religion.png',
	hindu_temple: './ico/religion.png',
	mosque: './ico/religion.png',
	synagogue: './ico/religion.png',

	//Виды спорта
	gym: './ico/sport-soccer.png',
	athletic_field: './ico/sport-soccer.png',
	fitness_center: './ico/sport-soccer.png',
	golf_course: './ico/sport-soccer.png',
	playground: './ico/sport-soccer.png',
	ski_resort: './ico/sport-soccer.png',
	sports_club: './ico/sport-soccer.png',
	sports_complex: './ico/sport-soccer.png',
	stadium: './ico/sport-soccer.png',
	swimming_pool: './ico/sport-soccer.png',

	//Еда и Напитки
	american_restaurant: './ico/food.png',
	barbecue_restaurant: './ico/food.png',
	brazilian_restaurant: './ico/food.png',
	breakfast_restaurant: './ico/food.png',
	brunch_restaurant: './ico/food.png',
	chinese_restaurant: './ico/food.png',
	fast_food_restaurant: './ico/food.png',
	french_restaurant: './ico/food.png',
	greek_restaurant: './ico/food.png',
	hamburger_restaurant: './ico/food.png',
	indian_restaurant: './ico/food.png',
	indonesian_restaurant: './ico/food.png',
	italian_restaurant: './ico/food.png',
	japanese_restaurant: './ico/food.png',
	korean_restaurant: './ico/food.png',
	lebanese_restaurant: './ico/food.png',
	mediterranean_restaurant: './ico/food.png',
	mexican_restaurant: './ico/food.png',
	middle_eastern_restaurant: './ico/food.png',
	pizza_restaurant: './ico/food.png',
	ramen_restaurant: './ico/food.png',
	restaurant: './ico/food.png',
	thai_restaurant: './ico/food.png',
	turkish_restaurant: './ico/food.png',
	vegan_restaurant: './ico/food.png',
	vegetarian_restaurant: './ico/food.png',
	vietnamese_restaurant: './ico/food.png',
	sushi_restaurant: './ico/food.png',
	seafood_restaurant: './ico/food.png',
	spanish_restaurant: './ico/food.png',
	meal_delivery: './ico/food.png',
	meal_takeaway: './ico/food.png',
	sandwich_shop: './ico/food.png',
	steak_house: './ico/food.png',

	bakery: './ico/coffee.png',
	bar: './ico/coffee.png',
	cafe: './ico/coffee.png',
	coffee_shop: './ico/coffee.png',
	ice_cream_shop: './ico/coffee.png',

	//Покупка
	auto_parts_store: './ico/solar_shop.png',
	book_store: './ico/solar_shop.png',
	cell_phone_store: './ico/solar_shop.png',
	clothing_store: './ico/solar_shop.png',
	convenience_store: './ico/solar_shop.png',
	department_store: './ico/solar_shop.png',
	discount_store: './ico/solar_shop.png',
	electronics_store: './ico/solar_shop.png',
	furniture_store: './ico/solar_shop.png',
	gift_shop: './ico/solar_shop.png',
	grocery_store: './ico/solar_shop.png',
	hardware_store: './ico/solar_shop.png',
	home_goods_store: './ico/solar_shop.png',
	home_improvement_store: './ico/solar_shop.png',
	jewelry_store: './ico/solar_shop.png',
	liquor_store: './ico/solar_shop.png',
	market: './ico/solar_shop.png',
	pet_store: './ico/solar_shop.png',
	shoe_store: './ico/solar_shop.png',
	shopping_mall: './ico/solar_shop.png',
	sporting_goods_store: './ico/solar_shop.png',
	store: './ico/solar_shop.png',
	supermarket: './ico/solar_shop.png',
	wholesaler: './ico/solar_shop.png',

	// Велосипеды
	bicycle_store: './ico/bicycle.png',

	//Развлечение
	night_club: './ico/18+.png',

	dog_park: './ico/nature.png',
	national_park: './ico/nature.png',
	park: './ico/nature.png',
	zoo: './ico/nature.png',

	tourist_attraction: './ico/ferris.png',
	visitor_center: './ico/ferris.png',
	wedding_venue: './ico/ferris.png',
	amusement_center: './ico/ferris.png',
	amusement_park: './ico/ferris.png',
	aquarium: './ico/ferris.png',
	banquet_hall: './ico/ferris.png',
	bowling_alley: './ico/ferris.png',
	community_center: './ico/ferris.png',
	convention_center: './ico/ferris.png',
	cultural_center: './ico/ferris.png',
	event_venue: './ico/ferris.png',
	hiking_area: './ico/ferris.png',
	historical_landmark: './ico/ferris.png',
	marina: './ico/ferris.png',
	movie_rental: './ico/ferris.png',
	movie_theater: './ico/ferris.png',
	casino: './ico/ferris.png',

	//Транспорт
	airport: './ico/factory.png',
	bus_station: './ico/factory.png',
	bus_stop: './ico/factory.png',
	ferry_terminal: './ico/factory.png',
	heliport: './ico/factory.png',
	light_rail_station: './ico/factory.png',
	park_and_ride: './ico/factory.png',
	subway_station: './ico/factory.png',
	taxi_stand: './ico/factory.png',
	train_station: './ico/factory.png',
	transit_depot: './ico/factory.png',
	transit_station: './ico/factory.png',
	truck_stop: './ico/factory.png',
	//
}
